CREATE TABLE course
(
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id  BIGINT                                  NOT NULL,
    course_no INTEGER                                 NOT NULL,
    cook      TEXT                                    NOT NULL,
    dish_id   BIGINT,
    wine_id   BIGINT,
    CONSTRAINT pk_course PRIMARY KEY (course_id)
);

CREATE TABLE dish
(
    dish_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            TEXT                                    NOT NULL,
    main_ingredient TEXT,
    CONSTRAINT pk_dish PRIMARY KEY (dish_id)
);

CREATE TABLE event
(
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date     date                                    NOT NULL,
    host     TEXT                                    NOT NULL,
    location TEXT,
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

CREATE TABLE wine
(
    wine_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    TEXT                                    NOT NULL,
    type    VARCHAR(255)                            NOT NULL,
    grape   TEXT                                    NOT NULL,
    country TEXT                                    NOT NULL,
    region  TEXT,
    year    SMALLINT,
    CONSTRAINT pk_wine PRIMARY KEY (wine_id)
);

ALTER TABLE course
    ADD CONSTRAINT uc_course_dish UNIQUE (dish_id);

ALTER TABLE course
    ADD CONSTRAINT FK_COURSE_ON_DISH FOREIGN KEY (dish_id) REFERENCES dish (dish_id);

CREATE INDEX IDX_COURSE_ON_EVENT ON course (event_id);

ALTER TABLE course
    ADD CONSTRAINT FK_COURSE_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (event_id);

CREATE INDEX IDX_COURSE_ON_WINE ON course (wine_id);

ALTER TABLE course
    ADD CONSTRAINT FK_COURSE_ON_WINE FOREIGN KEY (wine_id) REFERENCES wine (wine_id);