ALTER TABLE wine
    ALTER COLUMN country DROP NOT NULL;
ALTER TABLE wine
    RENAME COLUMN year TO vintage;
ALTER TABLE wine
    ADD COLUMN winery TEXT;
ALTER TABLE wine
    ADD COLUMN appellation TEXT;
ALTER TABLE wine
    ADD COLUMN vivino_url TEXT;

CREATE TABLE wine_style
(
    wine_style_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          TEXT                                 NOT NULL,
    CONSTRAINT pk_wine_style PRIMARY KEY (wine_style_id),
    CONSTRAINT uq_wine_style__style UNIQUE (name)
);

CREATE TABLE wine_styles
(
    wine_id       BIGINT NOT NULL,
    wine_style_id INT    NOT NULL,
    CONSTRAINT pk_wine_styles PRIMARY KEY (wine_id, wine_style_id),
    CONSTRAINT fk_wine_styles__wine FOREIGN KEY (wine_id) REFERENCES wine (wine_id) ON DELETE CASCADE,
    CONSTRAINT fk_wine_styles__style FOREIGN KEY (wine_style_id) REFERENCES wine_style (wine_style_id) ON DELETE CASCADE
);

CREATE INDEX ix_wine_styles__wine_style_id ON wine_styles (wine_style_id);

INSERT INTO wine_style (name)
SELECT DISTINCT type
FROM wine;

INSERT INTO wine_styles (wine_id, wine_style_id)
SELECT w.wine_id, ws.wine_style_id
FROM wine AS w
         JOIN wine_style AS ws ON w.type = ws.name;

ALTER TABLE wine
    DROP COLUMN type;

CREATE TABLE grape
(
    grape_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     TEXT                                 NOT NULL,
    CONSTRAINT pk_grape PRIMARY KEY (grape_id),
    CONSTRAINT uq_grape__name UNIQUE (name)
);

CREATE TABLE wine_grape_composition
(
    wine_id    BIGINT NOT NULL,
    grape_id   INT    NOT NULL,
    percentage NUMERIC(4, 3),
    CONSTRAINT pk_wine_grape_composition PRIMARY KEY (wine_id, grape_id),
    CONSTRAINT fk_wine_grape_composition__wine FOREIGN KEY (wine_id) REFERENCES wine (wine_id) ON DELETE CASCADE,
    CONSTRAINT fk_wine_grape_composition__grape FOREIGN KEY (grape_id) REFERENCES grape (grape_id) ON DELETE CASCADE,
    CONSTRAINT ch_wine_grape_composition__percentage CHECK (percentage BETWEEN 0 AND 1)
);

CREATE INDEX ix_wine_grape_composition__grape_id ON wine_grape_composition (grape_id);

INSERT INTO grape (name)
SELECT DISTINCT grape
FROM wine;

INSERT INTO wine_grape_composition (wine_id, grape_id, percentage)
SELECT w.wine_id, g.grape_id, 1
FROM wine AS w
         JOIN grape AS g ON w.grape = g.name;

ALTER TABLE wine
    DROP COLUMN grape;