name: Tests

on:
  push:
    branches:
      - "**"
      - "!main"
    paths-ignore: # Skip when only these files change
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
    env:
      GCP_CREDENTIALS_PATH: ./secrets/gcp-credentials.json

    steps:
      - uses: actions/checkout@v4

      - name: Setup configuration
        run: |
          mkdir secrets
          echo '${{ secrets.GCP_CREDENTIALS }}' >> secrets/gcp-credentials.json

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run All Tets
        run: ./mvnw verify

      - name: Upload Test Reports
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/target/surefire-reports
            **/target/failsafe-reports
          retention-days: 5

      - name: Report Unit Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit Test Results
          path: '**/target/surefire-reports/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true

      - name: Report Integration Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Integration Test Results
          path: '**/target/failsafe-reports/TEST-*.xml'
          reporter: java-junit
          fail-on-error: true

      - name: Cleanup
        if: always()
        run: rm -rf secrets